server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

spring:
  profiles:
    include: aws
  output.ansi.enabled: always
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update # create, update, none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    #show-sql: true
    format-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: test
    defer-datasource-initialization: true

  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zome: Asia/Seoul


app:
  jwtSecret: jwtsigntutorialasdfasdfasdfasdfasdf
  jwtExpirationInMs: 604800000

#  servlet:
#    multipart:
#      enabled: true
#      max-file-size: 2MB

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace